name: API Playwright ALL

on:
  schedule:
    - cron: "30 20 * * *"
  workflow_dispatch:

jobs:
  test_qa:
    name: "API QA ALL"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npx playwright install
      - run: npx playwright install-deps

      - name: Manage Secrets
        env:
          S3_QA_CREDENTIALS: ${{ secrets.S3_QA_CREDENTIALS }}
        run: echo "S3_QA_CREDENTIALS=$S3_QA_CREDENTIALS" > .env
      - name: "Test Execution"
        run: "npm run api:qa:all"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-qa
          path: |
            report-dir
          retention-days: 3

  test_staging:
    needs: test_qa
    if: always()
    name: "API STAGING ALL"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npx playwright install
      - run: npx playwright install-deps

      - name: Manage Secrets
        env:
          S3_QA_CREDENTIALS: ${{ secrets.S3_QA_CREDENTIALS }}
        run: echo "S3_QA_CREDENTIALS=$S3_QA_CREDENTIALS" > .env
      - name: "Test Execution"
        run: "npm run api:staging:all"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-staging
          path: |
            report-dir
          retention-days: 3
