name: Outcomes Functional Testing QA (WEB)

on:
  schedule:
    - cron: "30 21 * * *"
  workflow_dispatch:

jobs:
  test_chromium:
    name: "Outcomes Functional Testing QA (Chrome)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npx playwright install
      - run: npx playwright install-deps

      - name: Manage Secrets
        env:
          S3_QA_CREDENTIALS: ${{ secrets.S3_QA_CREDENTIALS }}
        run: echo "S3_QA_CREDENTIALS=$S3_QA_CREDENTIALS" > .env
      - name: "Test Execution"
        run: "npm run ui:outcomes:functional:qa"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-chromium
          path: |
            report-dir
          retention-days: 3

  test_webkit:
    needs: test_chromium
    if: always()
    name: "Outcomes Functional Testing QA (Webkit)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npx playwright install
      - run: npx playwright install-deps

      - name: Manage Secrets
        env:
          S3_QA_CREDENTIALS: ${{ secrets.S3_QA_CREDENTIALS }}
        run: echo "S3_QA_CREDENTIALS=$S3_QA_CREDENTIALS" > .env
      - name: "Test Execution"
        run: "npm run ui:outcomes:functional:qa:webkit"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-webkit
          path: |
            report-dir
          retention-days: 3
