name: Review Portal Functional QA (WEB)

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  test_auto:
    name: "Review Portal Functional QA (WEB)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npx playwright install
      - run: npx playwright install-deps

      - name: Manage Secrets
        env:
          S3_QA_CREDENTIALS: ${{ secrets.S3_QA_CREDENTIALS }}
        run: echo "S3_QA_CREDENTIALS=$S3_QA_CREDENTIALS" > .env
      - name: "Test Execution"
        run: "npm run ui:review-portal:functional:qa"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-web
          path: |
            report-dir
          retention-days: 3

  test_iphone:
    needs: test_auto
    if: always()
    name: "Review Portal Functional QA (IPhone XR)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npx playwright install
      - run: npx playwright install-deps

      - name: Manage Secrets
        env:
          S3_QA_CREDENTIALS: ${{ secrets.S3_QA_CREDENTIALS }}
        run: echo "S3_QA_CREDENTIALS=$S3_QA_CREDENTIALS" > .env
      - name: "Test Execution"
        run: "npm run ui:review-portal:functional:qa:iphone"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-iphone
          path: |
            report-dir
          retention-days: 3

  test_ipad:
    needs: test_iphone
    if: always()
    name: "Review Portal Functional QA (iPad 11 Pro)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npx playwright install
      - run: npx playwright install-deps

      - name: Manage Secrets
        env:
          S3_QA_CREDENTIALS: ${{ secrets.S3_QA_CREDENTIALS }}
        run: echo "S3_QA_CREDENTIALS=$S3_QA_CREDENTIALS" > .env
      - name: "Test Execution"
        run: "npm run ui:review-portal:functional:qa:ipad"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-ipad
          path: |
            report-dir
          retention-days: 3
